### ISSUE TITLE
Can I create C++ project inside a subfolder

### ISSUE THREAD

**Issue by ThantZinOo** [acharluk/easy-cpp-projects#9]
I means moving everything inside a subfolder , including build.bat, [include],[lib],[bin], ect.
I like to work from subfolder while maintaining external file at the same time.

**Comment by acharluk** [comment]
I haven't really considered this idea, right now the extension recognizes the folder you open, so if you open just the subfolder it should work fine. You can have multiple folders opened at the same time too if you want and it will ask you what project you want to build. I don't really know what you mean by maintaining an external file🤔🤔

**Comment by ThantZinOo** [comment]
thanks for the reply,
that's what I am doing right now. external file, I means is file from other project and relative path. some of the header file are outside my project and I like to browse and edit in same windows while working on my project.

**Comment by aleksamiskin** [comment]
I for example have a 3-level folder structure... with workplace option in Code you can solve 2-levels but three, no way... It would be nice to implement some type of support for subfolder menagement instead of autocreate in opened root folder.

**Comment by acharluk** [comment]
I've been thinking of this idea and I don't think it is possible for now. The easiest way to do this would be having a workspace with any number of folders opened in it, so that VSCode can recognize the tasks for each project (it detects it automatically in the root of the folder).

I am a student too and I have folders and subfolders for different assignments. I work with multiple folders in a single workspace like shown below, the extension handles this perfectly as it treats each folder as a different root.

This will not be implemented in this extension (maybe in a future one :wink:)

![image](https://user-images.githubusercontent.com/5154281/60197581-eee72c80-983f-11e9-89d3-9fcf093509ff.png)

![image](https://user-images.githubusercontent.com/5154281/60197620-01f9fc80-9840-11e9-8263-a9c1dbc160ba.png)
